# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_web_browser(object):
    def setupUi(self, web_browser):
        web_browser.setObjectName("web_browser")
        web_browser.resize(600, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(web_browser)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.web_browser_2 = QtWebEngineWidgets.QWebEngineView(web_browser)
        self.web_browser_2.setObjectName("web_browser_2")
        self.horizontalLayout.addWidget(self.web_browser_2)
        self.web_browser_2.resize(600, 600)

        self.retranslateUi(web_browser)
        QtCore.QMetaObject.connectSlotsByName(web_browser)

    def retranslateUi(self, web_browser):
        _translate = QtCore.QCoreApplication.translate
        web_browser.setWindowTitle(_translate("web_browser", "Web Browser"))
from PyQt5 import QtWebEngineWidgets
